contentdir: "content"
publishdir: "public"
baseurl: "http://elgris.github.io"
title: "creating software rocks!"
footnotereturnlinkcontents: "â†©"
permalinks:
  post: /:year/:month/:title/
params:
  Subtitle: "Welcome to exposed mind of little particle of our huge incredible world"
  AuthorName: "elgris"
  GitHubUser: "elgris"
  SidebarRecentLimit: 5
canonifyurls: true
theme: "liquorice"